[projectfinance]
type = "service_account"
project_id = "project-finance-493301"
private_key_id = "1cbe75d7494ce16f282a842d21410de2704de3a7"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCfzXOn6BBmc+vu
5TjxGVon+a6MLTwjm6TXeBz8z08DGTaMmXdns3QAMRSM0BnG5cD7IpLoLtzn7N4x
+tp3W06tHJ0JyJRl0BuIy9pLm7afod8V4Np5MQl74j86XrTE3movAm2Q7alskyxX
HDiMlmYCrloF9yEzSYy1VjYoxzimr1LDDIi7QM7BTB3vsgFXeFmA6rwc7mf18pxM
DoU3jbRFpez/vE1FLBLYzJrkpVzr9IV+h5VUx/YleeqcWl2/vm/hzXsmKpS8i1uc
k/uU6En8SY33Y9mEbD93WSaqYYP0kJWi9Run2x8BYOy5lVolV+b7byh4dKick6PN
yQTZ/BKBAgMBAAECggEALG1F9ixCQvl/Yk8/4WeW9P4pVLdOvOeMkIrIJFDOOqJL
1BLma2IsodEDUZKZV/6QBEG8beh5adEkhOikzAIKgX4u+oVVHGka/pEOA28q+n5a
Mw7sLj0/0b04rtWdlA3xn1ghdeVc8N6JuT4TSqKVgbFPPdFS3ZtZDyEEtZmNWml7
EoCLkUA0e51X7sDQ+rQDjTnpctsORnjpff+MNANpnD/xpOP7fFHlcyRWvsqGGl1C
uirAtHTXm4HwTXaZEBacYN/h7i9CmAMLL/aw1rAyaT3xvK46OzbtquzGAfaV6hsS
gcYcebIKNYaH1Q+V0b588XgD6WW5UO+FrGaxzO3jsQKBgQDUmPexMuuQ+0dI5xId
ikW0o6kaKb47yg6qOAoqdrYwAq0PdbID0thTptMW7iUfZCktXMfGBwkFEcROg/lb
t/nGWI3XZFBojY+YP3coc7cQyPUw0d0dGqJWSrlwFIHNgwPsAXAtA0ovaEeUQJLW
CUcgF8Rk5GCRooJA1cKiF+GvZwKBgQDAbT+Gvr1b9N2cCySkhl6P8JG9MnbqOZ14
BdbpkZTWmiz+hJ83g4/NSY3rGxISaTq4o3+y/S/LXEz23qzJ9ZA4ILWRdmmWzxRy
cmMCfRFlzf4NTYrpBHC0tjpslc8w5d+qEZPLS2T8wWKri4Iqng5vU8bKE/igBB3F
RGX0U51F1wKBgQCUknJHO7a0k2a15AYc7szX+KfsyM9RKVwmSRORqXSZCMW40B+f
3HGhxCwxEiyPS4gbU4OpOLFtAYWW+VQCbQf5PVmi9U/cQVHgrDmx42xEJqxzebZ0
6HAarg357drorG7JOBgU3P+zMcUULixvt/wkyXdOqutx24f7l2d1sArgcQKBgH/5
qGAzBrjbl28qMgqBmu5b7nFH2LJZ8xJZv97DBZvcGcSD62f+RWsgWhRcgp5gAb++
bTVbEahMEJu26G/As1PA3UCK4hp8Snr6/EIxb5qnbyjlw1bJrzNgZmbFE3DP0PrI
ieSQle9LphW0yLMTP0JnEzReJ+I0GqCRpsThvx0tAoGBAL9y0DNDPMBQNxDeFCWI
4VWMwEEqiqiWamracHnwAfeTOmWphUUc5llohOWIvUN3/z9ZlgpxQkASN8wM7zXs
FBQNht6qLHtXFA92GWNBoRNNLKdG+D9R395R7825Ut3Rum62t8lwa/d+Dd2NZIxC
SFPS5rWpVQdFXXMSX9nkT0mq
-----END PRIVATE KEY-----
"""
client_email = "project-finance@project-finance-493301.iam.gserviceaccount.com"
client_id = "101905048322480076545"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/project-finance%40project-finance-493301.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
