[projectfinance]
type = "service_account"
project_id = "project-finance-493301"
private_key_id = "a8685f58e3e846f64b29a762a5880da94cce7a03"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDfF5bFi44kVS/g
N46EnbarsFhKEvvnD208hd3iqvyEBB8uEGrmCUbJLsJLb15pblG8ml+UhGYGJYFD
1AImIaxPfZ0ASOWLwok0+K1rYpaff+ZD871D3mg0FKIYiw1pbUCGUP0/j23Vw9zp
EGP70HPoSsJ/I9E93wAK4X8JmkqIkpgv78xTJRfAt25v0CS4Vh8W6iqUaxiuhlPZ
NPKs9dYeJQoflxmi5qkbcqppA9JrqVtpcW1fRLzADwdvNyJ5vxNY7x5yRv9S9DKF
MEDmJ63KR0dpzlROXpP6FANRl0EgY7rf9n+cBF512UacWZGz1ax+m+iKbuAMx77g
u+5xnKSnAgMBAAECggEAR4Hpn2dEh+vQPTfBlEtzJmQPYKrmGGFu+6PTA9kXuH8T
uXGkuhhGGq1EtOY9JmEojOIUeefYRecWoHWfvLY1Y4NZZCJ5hUs1LIf7Gj0PF4/o
8GX7h/oNf4gPjvtfMKhGsubZzdo88/RkZkYNLkVaKZ5w6kzCQGkuu84cqKjOdCij
Zc1Y+e3KrOx7rFUKV4Y4WvEjX5Ti1H+PhP30lOpvpSzYUoWdyhblGYSwYpUtPA2W
bkaWcBN+2reQh1eEbqp7yJExS8i1oNQw1VnyI7DZXy16JOvAkalcNf2XfrXq43DY
Ns/h7TrT/boVtI9ers/wWh8vpw4z367x6wBJc3B1OQKBgQD+MPu5eXJ0LaHG/iHB
JdDiHdeAHHJEzn7RZSN2hMQuG/57OOAaL4MGMTMnHaVLdR20jk6m/7z3qLxRhbHJ
uTiObVzBd8TuOKU3pZKSthSI8fM6kTdVNFNCNWiyrAuPlJm1oZbqcQI1RTxU9ls0
JqQUMZNaobaSrgqD6i2gqcQHzwKBgQDgrfUkhhmPfPz3/o0B6EV9sc4eMN8ggBvv
LSqWtRJyBRsjqOxDG9sf7WOFCKcChXFgoC0kp1KymF58bbvfbNJ2Fp8eRatkmwhk
geDlc+ylNp5imVqyYaLIjcntnrKkGxiJm40+TMAU9yO/fHXdhAvO3CwAilRfQvSp
CkidYBbzqQKBgQDF2tLVN9cC31IBVmZntUu19Yx8R6gaLrE/w/2qjwU07s1SlJ67
Qyg1da5fUBANgAezNuG5023/R/PtcKdGYUnIcw+z98nts2HGwrYoRFoPjmTIvafY
RnZYHsJz8L6+7+gFHNYfff89/7pKV8f9++XTYhNUhHNcEORWcb06RWo0uQKBgG3W
vVxwrnhGa0k1yWugSLCtRw3daIdz+bQQyZxJw024j078mxwntxVBsYBs/XCvGgFZ
7RfZMQWclbyQzOLqSW1vm7Rp7ONPI2g3UmH6LTuLmxyqyfsg3jrbjlc7WSv/Dxze
zcsiLFlThMdtKhX0Iu2rF1vgRGUZz5AANgWx3yaZAoGBAN8L34rcsEDK1wbxSpsG
EEAl92ajx/6j6fb0Y11dcD/0PVXV/2tm8zZnmIxWdnZQLcxpV3A0DpEIPC/qhbuk
nnERCpRSe+JO834RiePpTJdOdOe4uIBSzyS5fHmwZ4h3KAxZLHKVjb+7LM4+32ez
RiZd69fKvoxBaWgrRWO0F1Jh
-----END PRIVATE KEY-----
"""
client_email = "project-finance@project-finance-493301.iam.gserviceaccount.com"
client_id = "101905048322480076545"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/project-finance%40project-finance-493301.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
